version: '3.9'

services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER:-portfolio_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-portfolio_password}
      POSTGRES_DB: portfolio_db
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    restart: unless-stopped
    env_file:
      - ./backend/env.example # переименуйте в .env для production
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build: ./frontend
    restart: unless-stopped
    env_file:
      - ./frontend/env.example # переименуйте в .env для production
    ports:
      - "3000:80" # в контейнере фронт обслуживает nginx
    depends_on:
      - backend

volumes:
  db_data: 